id: A090ED87C
title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
type: translation
pechas:
- I3D1EF4DA
- I120E1D8E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:53:02.785298
  last_modified_at: 2023-01-04 11:53:02.785307
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I3D1EF4DA/A996: CCD4
  I120E1D8E/96C8: CCD4
